const allRoles = {
    taker: [
        "getTest",
        "getTests",
        "getSubmission",
        "createSubmission",
        "getChats",
        "createMessage",
        "getMessages",
    ],
    maker: [
        "getTests",
        "getTest",
        "createTest",
        "updateTest",
        "deleteTest",
        "addPart",
        "updatePart",
        "validateParts",
        "createQuestion",
        "updateQuestion",
        "addAnswer",
        "createTaker",
        "getTakers",
        "assignTakers",
        "createTakersForTest",
        "getAvailableTakers",
        "validateQuestions",
        "getSubmissions",
        "getTakerSubmission",
        "publishTest",
        "updateTakerAnswer",
        "getTakersStatistics",
        "createChat",
        "createChats",
        "getChats",
        "createMessage",
        "getMessages",
    ],
    admin: ["getUsers", "manageUsers"],
};

export const roles = Object.keys(allRoles);
export const roleRights = new Map(Object.entries(allRoles));
