import { QUESTION_TYPE } from "./questionTypes.js";

export const AUTO_SCORE_TYPE = [
    QUESTION_TYPE.FILL_IN_THE_GAPS,
    QUESTION_TYPE.MATCHING,
    QUESTION_TYPE.MULTIPLE_CHOICES,
];

export const CHAT_OPTION = {
    INDIVIDUAL: "INDIVIDUAL",
    GROUP: "GROUP",
};

export const MANUAL_SCORE_TYPE = [QUESTION_TYPE.RESPONSE];
