export const MESSAGE_TYPE = {
    MESSAGE: "MESSAGE",
    NOTIFICATION: "NOTIFICATION",
};

export const NOTIFICATION_TYPE = {
    THEME_CHANGED: "THEME_CHANGED",
    NICK_NAME_CHANGED: "NICK_NAME_CHANGED",
    NICK_NAME_REMOVED: "NICK_NAME_REMOVED",
};
