export const QUESTION_TYPE = {
    MULTIPLE_CHOICES: "MULTIPLE_CHOICES",
    FILL_IN_THE_GAPS: "FILL_IN_THE_GAPS",
    TRUE_FALSE: "TRUE_FALSE",
    MATCHING: "MATCHING",
    RESPONSE: "RESPONSE",
};
