export const PAGINATION_MODE = {
    ONE_QUESTION: "ONE_QUESTION_PER_PAGE",
    ONE_PARTS: "ONE_PART_PER_PAGE",
    ALL: "ALL_QUESTIONS_PER_PAGE",
    FIXED_PER_PAGE: "FIXED_PER_PAGE",
};

export const QUESTION_NUMBERING_METHOD = {
    CONTINUOUS: "CONTINUOUS",
    PART_RESET: "PART_RESET",
};

export const RECORDING_MODE = {
    VIDEO: "VIDEO",
    SCREEN_SHOTS: "SCREEN_SHOTS",
};
